nodeGroupAutoDiscoveryLabel: "kube-shuffle-sharder.io/node-group"
tenantLabel: kube-shuffle-sharder.io/tenant
numNodeGroups: 2

webhookSecretName: ""
webhookCaBundle: ""

resources: 
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi