---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kube-shuffler-sharder-io-v1-nodegroups
  failurePolicy: Fail
  name: vnodegroups.kb.io
  rules:
  - apiGroups:
    - kube-shuffle-sharder.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodegroups
  sideEffects: None
