---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kube-shuffler-sharder.io
  resources:
  - shuffleshards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kube-shuffler-sharder.io
  resources:
  - shuffleshards/finalizers
  verbs:
  - update
- apiGroups:
  - kube-shuffler-sharder.io
  resources:
  - shuffleshards/status
  verbs:
  - get
  - patch
  - update
