apiVersion: kube-shuffle-sharder.io/v1
kind: NodeGroups
metadata:
  labels:
    app.kubernetes.io/name: nodegroups
    app.kubernetes.io/instance: nodegroups-sample
    app.kubernetes.io/part-of: kube-shuffle-sharder
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kube-shuffle-sharder
  name: nodegroups-sample
spec:
  # TODO(user): Add fields here
