name: Pull Request

on:
  push:
    branches:
      - **

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    # Setting up helm binary
    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        check-latest: true
        cache: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Test
      run: make test
